## 데이터 작업하기
파이토치(PyTorch)에는 데이터 작업을 위한 기본 요소 두가지인 torch.utils.data.DataLoader 와 torch.utils.data.Dataset 가 있습니다.


`Dataset` 은 샘플과 정답(label)을 저장하고, `DataLoader` 는 Dataset 을 반복 가능한 객체(iterable)로 감쌉니다.

In [2]:
import torch
from torch import nn 
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt

PyTorch는 `TorchText`, `TorchVision` 및 `TorchAudio` 와 같이 `도메인 특화 라이브러리를 데이터셋과 함께 제공`하고 있습니다. 이 튜토리얼에서는 TorchVision 데이터셋을 사용하도록 하겠습니다.

torchvision.datasets 모듈은 CIFAR, COCO 등과 같은 다양한 실제 비전(vision) 데이터에 대한 Dataset(전체 목록은 여기)을 포함하고 있습니다. 이 튜토리얼에서는 `FasionMNIST 데이터셋`을 사용합니다.

모든 TorchVision Dataset 은 샘플과 정답을 각각 변경하기 위한 `transform` 과 `target_transform` 의 두 인자를 포함합니다.

In [5]:
# 공개 데이터셋에서 학습 데이터를 내려받습니다.
training_data = datasets.FashionMNIST(
    root = "data",
    train = True,
    download=True,
    transform = ToTensor(),
)

#공개 데이터셋에서 테스트 데이터를 내려받습니다.
test_data = datasets.FashionMNIST(
    root = "data",
    train = False, 
    download = True,
    transform = ToTensor(),
)

In [9]:
print(len(training_data))
print(len(test_data))

60000
10000


`Dataset` 을 `DataLoader 의 인자로 전달`합니다.

이는 데이터셋을 `반복 가능한 객체(iterable)`로 감싸고, 자동화된 `배치(batch)`, `샘플링(sampling)`, `섞기(shuffle)` 및 `다중 프로세스로 데이터 불러오기(multiprocess data loading)`를 지원합니다.

여기서는 배치 크기(batch size)를 64로 정의합니다. 즉, 데이터로더(dataloader) 객체의 각 요소는 64개의 특징(feature)과 정답(label)을 묶음(batch)으로 반환합니다.

In [15]:
batch_size = 64

# 데이터로더를 생성합니다.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size = batch_size)

In [32]:
for X, y in test_dataloader : 
    print("Shape of X [N, C, H, W] : ", X.shape)
    print("Shape of y: " , y.shape, y.dtype)
    print(y)
    
# Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
# Shape of y:  torch.Size([64]) torch.int64

Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64
tensor([9, 2, 1, 1, 6, 1, 4, 6, 5, 7, 4, 5, 7, 3, 4, 1, 2, 4, 8, 0, 2, 5, 7, 9,
        1, 4, 6, 0, 9, 3, 8, 8, 3, 3, 8, 0, 7, 5, 7, 9, 6, 1, 3, 7, 6, 7, 2, 1,
        2, 2, 4, 4, 5, 8, 2, 2, 8, 4, 8, 0, 7, 7, 8, 5])
Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64
tensor([1, 1, 2, 3, 9, 8, 7, 0, 2, 6, 2, 3, 1, 2, 8, 4, 1, 8, 5, 9, 5, 0, 3, 2,
        0, 6, 5, 3, 6, 7, 1, 8, 0, 1, 4, 2, 3, 6, 7, 2, 7, 8, 5, 9, 9, 4, 2, 5,
        7, 0, 5, 2, 8, 6, 7, 8, 0, 0, 9, 9, 3, 0, 8, 4])
Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64
tensor([1, 5, 4, 1, 9, 1, 8, 6, 2, 1, 2, 5, 1, 0, 0, 0, 1, 6, 1, 6, 2, 2, 4, 4,
        1, 4, 5, 0, 4, 7, 9, 3, 7, 2, 3, 9, 0, 9, 4, 7, 4, 2, 0, 5, 2, 1, 2, 1,
        3, 0, 9, 1, 0, 9, 3, 6, 7, 9, 9, 4, 4, 7, 1, 2])
Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Sha

tensor([7, 6, 9, 9, 5, 5, 7, 0, 9, 3, 3, 6, 9, 8, 4, 2, 2, 3, 9, 4, 3, 6, 7, 3,
        0, 4, 8, 1, 8, 7, 3, 4, 5, 2, 2, 9, 1, 9, 4, 9, 1, 6, 2, 8, 8, 7, 7, 7,
        7, 2, 6, 0, 7, 5, 8, 5, 6, 0, 2, 4, 9, 2, 6, 1])
Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64
tensor([1, 9, 3, 1, 2, 2, 2, 3, 7, 5, 7, 4, 4, 4, 1, 2, 3, 5, 4, 2, 9, 1, 5, 9,
        3, 6, 6, 4, 0, 1, 7, 7, 4, 6, 7, 7, 3, 0, 4, 3, 2, 7, 8, 7, 2, 8, 0, 8,
        7, 4, 6, 2, 7, 0, 9, 9, 3, 1, 5, 9, 3, 1, 0, 3])
Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64
tensor([3, 5, 9, 7, 9, 8, 3, 5, 9, 3, 7, 9, 3, 4, 6, 6, 5, 7, 7, 6, 3, 5, 3, 1,
        1, 9, 4, 3, 9, 5, 5, 7, 2, 4, 9, 0, 2, 1, 9, 7, 1, 5, 0, 5, 5, 0, 3, 5,
        0, 3, 3, 7, 4, 2, 6, 8, 5, 9, 2, 1, 0, 5, 5, 8])
Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64
tensor([5, 3, 7, 4, 4, 3, 9, 6, 0, 0, 9, 1, 4, 3, 1, 5, 3,

tensor([7, 4, 2, 2, 3, 8, 0, 1, 9, 8, 0, 6, 2, 8, 3, 8, 0, 7, 6, 4, 3, 8, 1, 3,
        8, 7, 3, 0, 3, 4, 8, 8, 9, 1, 3, 2, 1, 4, 8, 0, 4, 6, 7, 3, 9, 4, 9, 0,
        4, 6, 5, 7, 0, 8, 1, 7, 5, 4, 9, 5, 7, 3, 2, 0])
Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64
tensor([9, 8, 7, 3, 7, 7, 4, 7, 5, 8, 5, 2, 4, 6, 2, 3, 8, 9, 7, 1, 3, 4, 2, 9,
        7, 1, 2, 2, 6, 0, 5, 5, 4, 5, 2, 8, 9, 4, 9, 9, 1, 4, 3, 1, 5, 5, 5, 6,
        8, 1, 5, 5, 9, 5, 9, 8, 3, 1, 1, 4, 6, 6, 9, 3])
Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64
tensor([6, 4, 4, 8, 6, 5, 4, 9, 0, 2, 8, 4, 8, 6, 3, 6, 1, 4, 3, 3, 8, 4, 9, 9,
        0, 7, 9, 5, 3, 1, 7, 2, 8, 4, 9, 6, 1, 6, 0, 5, 8, 1, 9, 3, 0, 8, 3, 8,
        4, 2, 5, 6, 9, 0, 1, 4, 0, 7, 9, 0, 1, 3, 9, 5])
Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64
tensor([1, 4, 1, 1, 4, 8, 3, 9, 5, 4, 4, 3, 7, 7, 7, 2, 3,

tensor([8, 8, 4, 6, 2, 0, 7, 0, 8, 9, 1, 6, 6, 7, 0, 8, 1, 8, 2, 4, 6, 7, 5, 7,
        9, 9, 3, 9, 4, 4, 6, 4, 1, 4, 8, 4, 2, 8, 6, 2, 2, 9, 1, 8, 0, 6, 2, 6,
        0, 3, 6, 6, 1, 3, 6, 3, 3, 1, 7, 8, 1, 0, 7, 6])
Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64
tensor([5, 0, 8, 2, 6, 5, 8, 7, 8, 4, 5, 9, 5, 5, 1, 2, 4, 7, 2, 9, 7, 8, 3, 7,
        4, 6, 3, 8, 8, 4, 5, 1, 8, 2, 6, 2, 2, 9, 8, 9, 0, 2, 5, 9, 3, 5, 9, 8,
        6, 3, 9, 5, 9, 3, 0, 8, 6, 0, 6, 3, 5, 8, 0, 6])
Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64
tensor([1, 8, 6, 9, 0, 0, 7, 6, 6, 8, 7, 6, 8, 8, 2, 0, 3, 6, 7, 1, 3, 7, 4, 0,
        7, 1, 6, 5, 2, 0, 7, 9, 0, 3, 8, 2, 1, 1, 8, 8, 3, 5, 7, 5, 6, 7, 4, 3,
        9, 3, 8, 9, 0, 4, 0, 4, 5, 7, 0, 4, 3, 9, 5, 7])
Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64
tensor([2, 2, 5, 8, 3, 1, 3, 5, 4, 9, 4, 3, 9, 9, 2, 0, 8,

tensor([1, 6, 3, 7, 5, 1, 2, 7, 7, 5, 8, 0, 9, 1, 0, 1, 6, 9, 1, 6, 5, 3, 3, 0,
        7, 1, 2, 7, 9, 3, 7, 4, 4, 4, 6, 7, 4, 7, 3, 1, 7, 8, 8, 7, 0, 1, 4, 0,
        9, 7, 9, 9, 1, 2, 0, 4, 7, 4, 3, 4, 1, 7, 5, 7])
Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64
tensor([0, 9, 0, 0, 3, 1, 4, 7, 9, 3, 6, 7, 8, 4, 7, 4, 0, 8, 3, 0, 1, 7, 9, 6,
        9, 1, 4, 6, 7, 1, 0, 6, 3, 7, 3, 1, 8, 6, 5, 9, 5, 8, 1, 0, 9, 2, 6, 2,
        1, 1, 4, 7, 3, 0, 7, 5, 8, 9, 5, 4, 0, 4, 7, 2])
Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64
tensor([3, 8, 3, 8, 1, 1, 2, 4, 8, 1, 6, 8, 1, 8, 5, 3, 2, 7, 2, 2, 4, 9, 6, 0,
        4, 9, 9, 6, 9, 9, 6, 7, 3, 4, 3, 3, 9, 4, 7, 7, 8, 1, 1, 6, 6, 5, 7, 9,
        4, 7, 6, 7, 0, 0, 2, 9, 9, 7, 7, 5, 0, 1, 4, 3])
Shape of X [N, C, H, W] :  torch.Size([64, 1, 28, 28])
Shape of y:  torch.Size([64]) torch.int64
tensor([4, 6, 4, 0, 9, 8, 7, 8, 4, 4, 8, 9, 7, 1, 6, 7, 9,

------------------------------------------

## 모델 만들기

신경망 모델은 `nn.Module` 을 상속받는 클래스(class)를 생성하여 정의합니다. 

`__init__` 함수에서 `신경망의 계층(layer)들을 정의`하고 
`forward` 함수에서 `신경망에 데이터를 어떻게 전달할지 지정`합니다.
가능한 경우 GPU로 신경망을 이동시켜 연산을 가속(accelerate)합니다.

In [14]:
# 학습에 사용할 CPU나 GPU 장치를 얻습니다.
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using {} device".format(device))

Using cpu device


super() : 자식 클래스에서 부모클래스의 내용을 사용하고 싶을경우 사용  

PyTorch의 `Module`은 Tensor를 Input으로 받아 무언가 처리하고 처리 결과 Tensor를 Output로 내보내 주는 Container입니다.

통상적으로는 torch.nn에 있는 여러 Module을 조합해서 새로운 Module을 만들고 싶을 때 PyTorch의 Module을 직접 정의해서 사용합니다. 여러 Module들을 조합해 서 새로운 Module을 만들어 주는 특별한 기능이 없는 단순한 Container로 보이지만 여러가지 잘 보이지 않는 중요한 기능을 가지고 있습니다.

Moduel : https://teamdable.github.io/techblog/PyTorch-Module

In [17]:
#모델을 정의합니다
class NeuralNetwork(nn.Module) :
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512,512),
            nn.ReLU(),
            nn.Linear(512,10),
            nn.ReLU()
        )
        
    def forward(self, x) :
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

NeuralNetwork 의 `인스턴스(instance)를 생성`하고 이를 `device 로 이동`한 뒤, `구조(structure)를 출력`합니다.

In [18]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten()
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
)


모델을 사용하기 위해 입력 데이터를 전달합니다.

이는 일부 `백그라운드 연산들` 과 함께 모델의 `forward 를 실행`합니다. **model.forward() 를 직접 호출하지 마세요!**

module.py : https://github.com/pytorch/pytorch/blob/270111b7b611d174967ed204776985cefca9c144/torch/nn/modules/module.py#L866

모델에 입력을 호출하면 각 분류(class)에 대한 원시(raw) 예측값이 있는 `10-차원 텐서`가 반환됩니다. 원시 예측값을 `nn.Softmax 모듈의 인스턴스에 통과시켜 예측 확률을 얻습니다.`

In [20]:
X = torch.rand(1,28,28, device = device)
logits = model(X)

In [21]:
logits

tensor([[0.0000, 0.0187, 0.0000, 0.1061, 0.0385, 0.0945, 0.1011, 0.0703, 0.0000,
         0.0172]], grad_fn=<ReluBackward0>)

In [30]:
logits

tensor([[0.0000, 0.0187, 0.0000, 0.1061, 0.0385, 0.0945, 0.1011, 0.0703, 0.0000,
         0.0172]], grad_fn=<ReluBackward0>)

In [31]:
loss_fn = nn.CrossEntropyLoss()

In [62]:
y = torch.tensor([test_data[0][1]])

In [63]:
loss_fn(logits, y)

tensor(2.3308, grad_fn=<NllLossBackward>)

In [64]:
logits.argmax(1) == y

tensor([False])

In [68]:
(logits.argmax(1) == y).type(torch.float)

tensor([0.])

In [69]:
(logits.argmax(1) == y).type(torch.float).sum()

tensor(0.)

In [70]:
(logits.argmax(1) == y).type(torch.float).sum().item()

0.0

In [66]:
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([3])


----------------------------

## 모델 매개변수 최적화하기

모델을 학습하려면 `손실 함수(loss function)` 와 `옵티마이저(optimizer)` 가 필요합니다.

In [25]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

각 학습 단계(training loop)에서 모델은 (배치(batch)로 제공되는) 학습 데이터셋에 대한 예측을 수행하고, 예측 오류를 역전파하여 모델의 매개변수를 조정합니다.

In [29]:
print(len(train_dataloader.dataset))
print(len(train_dataloader)) #batchsize 64
60000/64

60000
938


937.5

In [51]:
def train(dataloader, model, loss_fn, optimizer) :
    size = len(dataloader.dataset)
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device) #device로 이동
        
        #예측 오류 계산
        pred = model(X)
        loss = loss_fn(pred,y)
        
        #역전파
        optimizer.zero_grad() #0으로 초기화
        loss.backward()
        optimizer.step()
        
        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f} [{current:>5d}/{size:>5d}]")

모델이 학습하고 있는지를 확인하기 위해 테스트 데이터셋으로 모델의 성능을 확인합니다.

추론을 실행하기 전에는 반드시 `model.eval()` 을 호출하여 드롭아웃 및 배치 정규화를 평가 모드로 설정하여야 합니다. 이것을 하지 않으면 추론 결과가 일관성 없게 출력됩니다.

In [52]:
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    
    model.eval()
    test_loss, correct = 0,0
    with torch.no_grad() :
        for X, y in dataloader : 
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
            
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

학습 단계는 여러번의 반복 단계 `(에폭(epochs))` 를 거쳐서 수행됩니다. 각 에폭에서는 모델은 더 나은 예측을 하기 위해 매개변수를 학습합니다. 각 에폭마다 모델의 정확도(accuracy)와 손실(loss)을 출력합니다; 에폭마다 정확도가 증가하고 손실이 감소하는 것을 보려고 합니다.

In [54]:
epochs = 1
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
loss: 1.932362 [    0/60000]
loss: 1.856013 [ 6400/60000]
loss: 1.785633 [12800/60000]
loss: 1.813375 [19200/60000]
loss: 1.671468 [25600/60000]
loss: 1.759822 [32000/60000]
loss: 1.745724 [38400/60000]
loss: 1.725546 [44800/60000]
loss: 1.700321 [51200/60000]
loss: 1.588575 [57600/60000]
Test Error: 
 Accuracy: 58.6%, Avg loss: 1.618671 

Done!


-----------------------------

## 모델 저장하기

모델을 저장하는 일반적인 방법은 (모델의 매개변수들을 포함하여) `내부 상태 사전(internal state dictionary)`을 `직렬화(serialize)`하는 것입니다.

In [71]:
torch.save(model.state_dict(), "model/model.pth")
print("Saved PyTorch Model State to model.pth")

Saved PyTorch Model State to model.pth


## 모델 불러오기

모델을 불러오는 과정에는 `모델 구조를 다시 만들고` `상태 사전을 모델에 불러오는 과정`이 포함됩니다.

In [73]:
model = NeuralNetwork()
model.load_state_dict(torch.load("model/model.pth"))

<All keys matched successfully>

이제 이 모델을 사용해서 예측을 할 수 있습니다

In [75]:
classes = [
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot",
]

In [77]:
model.eval()
x, y = test_data[0][0], test_data[0][1]
with torch.no_grad() :
    pred = model(x)
    predicted, actual = classes[pred[0].argmax(0)], classes[y]
    print(f'Predicted: "{predicted}", Actual: "{actual}"')

Predicted: "Ankle boot", Actual: "Ankle boot"


argmax

**Parameters**
* input ( Tensor ) – 입력 텐서.
* dim (int) – the dimension to reduce. If None , the argmax of the flattened input is returned.
* keepdim ( bool ) – 출력 텐서가 dim 유지 되었는지 여부 . dim=None 이면 무시됩니다 .

In [82]:
pred.argmax(1)

tensor([9])

In [80]:
pred[0].argmax(0)

tensor(9)