# TENSOR

`텐서(tensor)`는 `배열(array)`이나 `행렬(matrix)`과 매우 유사한 특수한 자료구조입니다. PyTorch에서는 텐서를 사용하여 `모델의 입력(input)과 출력(output)`, 그리고 모델의 `매개변수들`을 `부호화(encode)`합니다.

텐서는 **GPU나 다른 하드웨어 가속기에서 실행할 수 있다**는 점만 제외하면 NumPy 의 ndarray와 유사합니다. 실제로 텐서와 NumPy 배열(array)은 종종 동일한 내부(underly) 메모리를 공유할 수 있어 데이터를 복수할 필요가 없습니다. (NumPy 변환(Bridge) 참고) 텐서는 또한 (Autograd 장에서 살펴볼) **자동 미분(automatic differentiation)에 최적화**되어 있습니다. ndarray에 익숙하다면 Tensor API를 바로 사용할 수 있을 것입니다. 

In [1]:
import torch
import numpy as np

C:\Users\bini\anaconda3\envs\anaconda\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\bini\anaconda3\envs\anaconda\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
C:\Users\bini\anaconda3\envs\anaconda\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)


## 텐서 초기화

**데이터로부터 직접(directly) 생성하기**


데이터로부터 직접 텐서를 생성할 수 있습니다. 데이터의 자료형(data type)은 자동으로 유추합니다.

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

**Numpy 배열로부터 생성하기**


텐서는 NumPy 배열로 생성할 수 있습니다. (그 반대도 가능합니다 - NumPy 변환(Bridge) 참고)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**다른 텐서로부터 생성하기**

명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))을 유지합니다.

In [6]:
x_data

tensor([[1, 2],
        [3, 4]])

In [9]:
# x_data의 속성을 유지합니다.
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [11]:
# x_data의 속성을 덮어씁니다.
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.4776, 0.6298],
        [0.0627, 0.3456]])

**무작위(random) 또는 상수(constant) 값을 사용하기:**

`shape` 은 `텐서의 차원(dimension)을 나타내는 튜플(tuple)`로, 아래 함수들에서는 출력 텐서의 차원을 결정합니다.

In [12]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9285, 0.2050, 0.4485],
        [0.7818, 0.9149, 0.9811]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


-------------------

## 텐서의 속성(Attribute)

텐서의 속성은 `텐서의 모양(shape)`, `자료형(datatype)` 및 `어느 장치에 저장`되는지를 나타냅니다.

In [13]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


--------------------

## 텐서 연산(Operation)

전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링(random sampling) 등, 100가지 이상의 텐서 연산들을 여기 에서 확인할 수 있습니다.

각 연산들은 (일반적으로 CPU보다 빠른) GPU에서 실행할 수 있습니다. Colab을 사용한다면, Edit > Notebook Settings 에서 GPU를 할당할 수 있습니다.

**기본적으로 텐서는 CPU에 생성됩니다. .to 메소드를 사용하면 (GPU의 가용성(availability)을 확인한 뒤) GPU로 텐서를 명시적으로 이동할 수 있습니다.** 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이든다는 것을 기억하세요!

In [15]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [16]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.3130, 0.2654, 0.1445, 0.2719],
        [0.2094, 0.1580, 0.0025, 0.5800],
        [0.1540, 0.8031, 0.0014, 0.1013]])

**단일-요소(single-element) 텐서 **

텐서의 모든 값을 하나로 집계(aggregate)하여 `요소가 하나인 텐서의 경우`, `item()` 을 사용하여 `Python 숫자 값으로 변환`할 수 있습니다:

In [17]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

5.286165714263916 <class 'float'>


**바꿔치기(in-place) 연산**

연산 결과를 피연산자(operand)에 저장하는 연산을 바꿔치기 연산이라고 부르며,` _ 접미사`를 갖습니다. 예를 들어: `x.copy_(y)` 나 `x.t_()` 는 `x 를 변경`합니다.

In [18]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[0.5594, 0.5151, 0.3802, 0.5215],
        [0.4577, 0.3974, 0.0496, 0.7616],
        [0.3924, 0.8961, 0.0368, 0.3183]]) 

tensor([[5.5594, 5.5151, 5.3802, 5.5215],
        [5.4577, 5.3974, 5.0496, 5.7616],
        [5.3924, 5.8961, 5.0368, 5.3183]])


바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있습니다. 따라서, `사용을 권장하지 않습니다.`

-------------------------

## NumPy 변환(Bridge)

**CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유**하기 때문에, 하나를 변경하면 **다른 하나도 변경**됩니다.

In [20]:
#텐서를 NumPy 배열로 변환하기

t = torch.ones(5)
print(t)

n = t.numpy()
n

tensor([1., 1., 1., 1., 1.])


array([1., 1., 1., 1., 1.], dtype=float32)

텐서의 변경 사항이 NumPy 배열에 반영됩니다.

In [21]:
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
# NumPy 배열을 텐서로 변환하기

n = np.ones(5)
t = torch.from_numpy(n)

NumPy 배열의 변경 사항이 텐서에 반영됩니다.

In [23]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
